<!--#if (CopyrightHeader) -->
<!--
// Copyright (C) 2026 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
-->
<!--#endif -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="__QT_BRIDGE_PACKAGE_ID__" Version="__PACKAGE_VERSION__" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Main.qml"/>
    <Compile Include="Program.cs" />
  </ItemGroup>

</Project>
