<!--
// Copyright (C) 2026 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
-->

<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$([MSBuild]::GetPathOfFileAbove(qt_version.props))" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace>Qt.Bridge.CodeGeneration</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="10.0.0-rc.1.25451.107" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Qt.DotNet.Adapter\Qt.DotNet.Adapter.csproj" />
    <ProjectReference Include="..\Qt.Bridge.CSharp.Generator\Qt.Bridge.CSharp.Generator.csproj" />
    <ProjectReference Include="..\..\utils\Text\Text.csproj" />
  </ItemGroup>

</Project>
