<!--
// Copyright (C) 2026 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
-->

<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$([MSBuild]::GetPathOfFileAbove(qt_version.props))" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace></RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\utils\Collections\Collections.csproj" />
    <ProjectReference Include="..\..\utils\Concurrent\Concurrent.csproj" />
    <ProjectReference Include="..\..\utils\LazyFactory\LazyFactory.csproj" />
    <ProjectReference Include="..\..\utils\Text\Text.csproj" />
    <ProjectReference Include="..\Qt.DotNet.Adapter\Qt.DotNet.Adapter.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="'$(SolutionDir)' == ''">
    <SolutionDir>$(MSBuildThisFileDirectory)\..\..\</SolutionDir>
  </PropertyGroup>

</Project>
