<?xml version="1.0" encoding="utf-8"?>
<!--
// Copyright (C) 2026 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR BSD-3-Clause
-->

<Project>

  <Import Project="$([MSBuild]::GetPathOfFileAbove(qt_version.props))" />
  <Import Project="$([MSBuild]::GetPathOfFileAbove(qt_rid.props))" />
  <Import Project="$([MSBuild]::GetPathOfFileAbove(qt_bridge_package.props))" />

  <Import Project="Sdk.props" Sdk="Microsoft.NET.Sdk" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup Condition="'$(SolutionName)' != 'qtbridge-csharp'">
    <PackageReference Include="$(QtBridgePackageId)" Version="$(SelectedVersion)" />
  </ItemGroup>

  <ItemGroup Condition="'$(SolutionName)' == 'qtbridge-csharp'">
    <ProjectReference
      Include="..\..\src\Qt.DotNet.Adapter\Qt.DotNet.Adapter.csproj" />
    <ProjectReference
      Include="..\..\src\Qt.Bridge.CSharp.Generator\Qt.Bridge.CSharp.Generator.csproj" />
    <ProjectReference
      Include="..\..\src\Qt.Bridge.CSharp.GenerationRules\Qt.Bridge.CSharp.GenerationRules.csproj"/>
  </ItemGroup>
  <Import
    Condition="'$(SolutionName)' == 'qtbridge-csharp'" Project="..\..\build\Qt.Bridge.targets" />

  <Import Project="Sdk.targets" Sdk="Microsoft.NET.Sdk" />

</Project>
