<!--
/***************************************************************************************************
 Copyright (C) 2025 The Qt Company Ltd.
 SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only OR GPL-2.0-only OR GPL-3.0-only
***************************************************************************************************/
-->

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace></RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(SolutionDir)' == ''">
    <SolutionDir>$(MSBuildThisFileDirectory)\..\..\</SolutionDir>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="MKDIR $(SolutionDir)bin 2&gt; NUL&#xD;&#xA;COPY $(OutputPath)$(AssemblyName).dll $(SolutionDir)bin\$(AssemblyName).dll&#xD;&#xA;" />
  </Target>
  <Target Name="CleanPostBuild" AfterTargets="Clean">
    <Delete Files="$(SolutionDir)bin\$(AssemblyName).dll" />
  </Target>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Test_Qt.DotNet.Adapter</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <Import Project="includegen.targets" />

</Project>
