<!--
// Copyright (C) 2026 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
-->

<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$([MSBuild]::GetPathOfFileAbove(qt_version.props))" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <RootNamespace></RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\utils\Text\Text.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="'$(SolutionDir)' == ''">
    <SolutionDir>$(MSBuildThisFileDirectory)\..\..\</SolutionDir>
  </PropertyGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="MKDIR $(SolutionDir)bin 2&gt; NUL&#xD;&#xA;COPY $(OutputPath)$(AssemblyName).dll $(SolutionDir)bin\$(AssemblyName).dll&#xD;&#xA;" />
  </Target>
  <Target Name="CleanPostBuild" AfterTargets="Clean">
    <Delete Files="$(SolutionDir)bin\$(AssemblyName).dll" />
  </Target>

  <Import Project="includegen.targets" />

</Project>
