<!--
// Copyright (C) 2026 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only
-->

<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$([MSBuild]::GetPathOfFileAbove(qt_version.props))" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AdapterInit\Program.cs" />
    <Compile Remove="BindingsAndInterfaces\Program.cs" />
    <Compile Remove="CollectionsAndValues\Program.cs" />
    <Compile Remove="CustomMarshaling\Program.cs" />
    <Compile Remove="DelegatesAndEvents\Program.cs" />
    <Compile Remove="FunctionCalls\Program.cs" />
    <Compile Remove="HostLifecycle\Program.cs" />
    <Compile Remove="Models\TableModel\Program.cs" />
    <Compile Remove="ObjectInterop\Program.cs" />
    <Compile Remove="QtQuickTest\Program.cs" />
    <Compile Remove="QtTest\Program.cs" />
    <Compile Remove="StructuredData\Program.cs" />
    <Compile Remove="WrapperTypes\Program.cs" />
    <None Remove="AdapterInit\main.cpp" />
    <None Remove="BindingsAndInterfaces\main.cpp" />
    <None Remove="BindingsAndInterfaces\TransformedTextSource.h" />
    <None Remove="BindingsAndInterfaces\TransformedTextSource.cpp" />
    <None Remove="CollectionsAndValues\main.cpp" />
    <None Remove="CustomMarshaling\main.cpp" />
    <None Remove="DelegatesAndEvents\main.cpp" />
    <None Remove="FunctionCalls\main.cpp" />
    <None Remove="HostLifecycle\main.cpp" />
    <None Remove="ObjectInterop\main.cpp" />
    <None Remove="QtQuickTest\main.cpp" />
    <None Remove="QtTest\main.cpp" />
    <None Remove="StructuredData\main.cpp" />
    <None Remove="WrapperTypes\main.cpp" />
    <None Remove="WrapperTypes\uri.h" />
    <None Remove="WrapperTypes\uri.cpp" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AdapterInit\main.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="AdapterInit\Program.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="BindingsAndInterfaces\main.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="BindingsAndInterfaces\Program.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="BindingsAndInterfaces\TransformedTextSource.h">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="BindingsAndInterfaces\TransformedTextSource.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="CollectionsAndValues\main.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="CollectionsAndValues\Program.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="CustomMarshaling\main.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="CustomMarshaling\Program.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DelegatesAndEvents\main.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="DelegatesAndEvents\Program.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="FunctionCalls\main.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="FunctionCalls\Program.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="HostLifecycle\main.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="HostLifecycle\Program.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Models\TableModel\main.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Models\TableModel\Program.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Models\TableModel\tst_tablemodel.qml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ObjectInterop\main.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ObjectInterop\Program.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="QtQuickTest\main.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="QtQuickTest\tst_qtquicktest.qml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="QtQuickTest\Program.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="QtTest\main.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="QtTest\Program.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Shared\QtTestSetupBase.h">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Shared\QtQuickTestSetup.h">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Shared\QtQuickTestSetup.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Shared\StringBuilder.h">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Shared\StringBuilder.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>

    <Content Include="StructuredData\main.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="StructuredData\tst_structureddata.qml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="StructuredData\Program.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="WrapperTypes\main.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="WrapperTypes\Program.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="WrapperTypes\uri.h">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="WrapperTypes\uri.cpp">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSBuild.StructuredLogger" Version="2.3.71" />
    <PackageReference Include="MSTest" Version="3.10.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.10.4" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\nuget\Qt.Bridge.CSharp.Package\Qt.Bridge.CSharp.Package.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <!-- Runtime access to build properties -->
  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>Build.ProjectDir</_Parameter1>
      <_Parameter2>$(ProjectDir)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
