<!--
// Copyright (C) 2026 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR GPL-3.0-only
-->
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$([MSBuild]::GetPathOfFileAbove(qt_version.props))" />
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12</LangVersion>
    <UseWPF>true</UseWPF>
    <VssdkCompatibleExtension>true</VssdkCompatibleExtension>
    <TargetVsixContainerName>Qt.Bridge.CSharp.vsix</TargetVsixContainerName>
    <NoWarn>$(NoWarn);VSEXTPREVIEW_LSP</NoWarn>
    <QtBridgeTemplatesPackageId>QtGroup.Qt.Bridge.CSharp.Templates</QtBridgeTemplatesPackageId>
    <QtBridgeTemplatesPackageFileName
      >$(QtBridgeTemplatesPackageId).$(SelectedVersion).nupkg</QtBridgeTemplatesPackageFileName>
    <QtBridgeTemplatesProjectPath
      >$(MSBuildThisFileDirectory)..\..\nuget\Qt.Bridge.CSharp.Templates\Qt.Bridge.CSharp.Templates.csproj</QtBridgeTemplatesProjectPath>
    <QtBridgeTemplatesPackagePath
      >$(MSBuildThisFileDirectory)..\..\nuget\Qt.Bridge.CSharp.Templates\bin\$(Configuration)\$(QtBridgeTemplatesPackageFileName)</QtBridgeTemplatesPackagePath>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="GPL-3.0-only.txt" />
    <None Remove="Templates.pkgdef" />
    <None Remove="qt.ico" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="GPL-3.0-only.txt">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="qt.ico">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
    <Content Include="Templates.pkgdef">
      <IncludeInVSIX>true</IncludeInVSIX>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Qt.Bridge.CSharp.VisualStudio.Core\Qt.Bridge.CSharp.VisualStudio.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.Extensibility.Sdk" Version="17.14.40608" PrivateAssets="all" />
    <PackageReference Include="Microsoft.VisualStudio.Extensibility.Build" Version="17.14.40608" PrivateAssets="all" />
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.14.40265" ExcludeAssets="runtime" />
  </ItemGroup>

  <Target Name="Build" Condition="!$([MSBuild]::IsOsPlatform('Windows'))">
    <Message Importance="High" Text="$(MSBuildProjectName): skipped (Windows only)" />
  </Target>

  <Target Name="EnsureQtBridgeTemplatesPackage" BeforeTargets="PreCreateVsixContainer">
    <MSBuild Projects="$(QtBridgeTemplatesProjectPath)"
      Targets="Pack"
      Properties="Configuration=$(Configuration)" />
  </Target>

  <Target Name="PreCreateVsixContainer" BeforeTargets="GetVsixSourceItems">
    <Error Text="No template package found at '$(QtBridgeTemplatesPackagePath)'."
      Condition="!Exists('$(QtBridgeTemplatesPackagePath)')" />
    <ItemGroup>
      <VSIXSourceItem Include="$(QtBridgeTemplatesPackagePath)">
        <VSIXSubPath>ProjectTemplates\</VSIXSubPath>
      </VSIXSourceItem>
    </ItemGroup>
  </Target>

</Project>
