<!--
// Copyright (C) 2026 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
-->

<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$([MSBuild]::GetPathOfFileAbove(qt_version.props))" />
  <Import Project="$([MSBuild]::GetPathOfFileAbove(qt_template.targets))" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>true</IsPackable>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>

    <PackageId>QtGroup.Qt.Bridge.CSharp.Templates</PackageId>
    <Authors>The Qt Company</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>Qt Bridge for C# - Templates</Description>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
    <PackageType>Template</PackageType>
    <IncludeContentInPack>true</IncludeContentInPack>
    <PackageTags>dotnet-new;templates;Qt.Bridge.CSharp</PackageTags>
  </PropertyGroup>

  <PropertyGroup>
    <LocalizeTemplates>false</LocalizeTemplates>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.TemplateEngine.Tasks"
                      Version="*" PrivateAssets="all" IsImplicitlyDefined="true" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="templates\**\*" PackagePath="content\"
             Exclude="templates\**\bin\**;templates\**\obj\**;templates/Qt.Bridge.CSharp.Project/NewProject.template.csproj" />
    <Compile Remove="**\*" />
  </ItemGroup>

  <ItemGroup>
    <!-- Placholder - Do not remove! -->
    <!-- Final README.md to be included in the NuGet package -->
    <None Include="README.md" Pack="true" PackagePath="" Visible="false"/>

    <!-- Templates remain in the project but are not packed into the NuGet -->
    <None Include="README.template.md" Pack="false" />
    <None Include="templates/Qt.Bridge.CSharp.Project/NewProject.template.csproj" Pack="false" />
  </ItemGroup>

  <Target Name="GenerateReadme" BeforeTargets="_GetPackageFiles">

    <ItemGroup>
      <!-- Tokens for README generation -->
      <QtTemplateToken Remove="@(QtTemplateToken)" />
      <QtTemplateToken Include="__PACKAGE_ID__">
        <ReplacementValue>$(PackageId)</ReplacementValue>
      </QtTemplateToken>
      <QtTemplateToken Include="__PACKAGE_VERSION__">
        <ReplacementValue>$(PackageVersion)</ReplacementValue>
      </QtTemplateToken>
    </ItemGroup>

    <QtTemplateFile Template="README.template.md"
                    OutputFileName="README.md"
                    Tokens="@(QtTemplateToken)" />
    <QtTemplateFile Template="templates/Qt.Bridge.CSharp.Project/NewProject.template.csproj"
                OutputFileName="templates/Qt.Bridge.CSharp.Project/NewProject.csproj"
                Tokens="@(QtTemplateToken)" />
  </Target>

  <Target Name="CopyPackage" AfterTargets="Pack">
    <PropertyGroup>
      <PackedNupkg>$(PackageOutputPath)$(PackageId).$(PackageVersion).nupkg</PackedNupkg>
    </PropertyGroup>

    <Message Importance="high"
             Text="Copy $(PackedNupkg) to $(MSBuildThisFileDirectory)..\local\$(PackageId)\$(PackageVersion)" />
    <Copy SourceFiles="$(PackedNupkg)"
          DestinationFolder="$(MSBuildThisFileDirectory)..\local\$(PackageId)\$(PackageVersion)" />
  </Target>
</Project>
