<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Hashing" Version="10.0.0-rc.1.25451.107" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Qt.DotNet.Generator\Qt.DotNet.Generator.csproj" />
  </ItemGroup>

</Project>
