<!--
// Copyright (C) 2026 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
-->

<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$([MSBuild]::GetPathOfFileAbove(qt_version.props))" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyName>qbgen</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.0-rc.1.25451.107" />
    <PackageReference Include="System.Reflection.MetadataLoadContext" Version="9.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\utils\Collections\Collections.csproj" />
    <ProjectReference Include="..\..\utils\Concurrent\Concurrent.csproj" />
    <ProjectReference Include="..\..\utils\LazyFactory\LazyFactory.csproj" />
    <ProjectReference Include="..\Qt.DotNet.Adapter\Qt.DotNet.Adapter.csproj" />
    <ProjectReference Include="..\Qt.Bridge.CSharp.Api\Qt.Bridge.CSharp.Api.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>Test_Qt.Bridge.CSharp.Generator</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
